WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
char = { 'a'..'z' | 'A'..'Z' | "_" }
digit = { '0'..'9' }

identifier = { char ~ (char | digit)* }
string_literal = { "\"" ~ ( !"\"" ~ ANY )* ~ "\"" }

send_stmt = { "send" ~ "(" ~ string_literal ~ ")" ~ ";" }
if_stmt = { "if" ~ "(" ~ identifier ~ ")" ~ "{" ~ body ~ "}" }
body = { (if_stmt | send_stmt)* }

vapor_func = { SOI ~ "vapor" ~ identifier ~ "(" ~ ")" ~ "{" ~ body ~ "}" ~ EOI }
