WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
char = { 'a'..'z' | 'A'..'Z' | "_" }
digit = { '0'..'9' }

identifier = { char ~ (char | digit)* }
number = { digit+ }
comparison_operator = { ">=" | "<=" | "==" | "!=" | ">" | "<" }
comparison = { identifier ~ comparison_operator ~ number }
condition = { comparison | identifier }

send_stmt = { "send" ~ "(" ~ string_literal ~ ")" ~ ";" }
if_stmt = { "if" ~ "(" ~ condition ~ ")" ~ "{" ~ body ~ "}" }
body = { (if_stmt | send_stmt)* }
string_literal = { """ ~ ( !""" ~ ANY )* ~ """ }

vapor_func = { SOI ~ "vapor" ~ identifier ~ "(" ~ ")" ~ "{" ~ body ~ "}" ~ EOI }
